# Generated by Django 5.0.7 on 2026-03-12 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_office'),
        ('administrator', '0002_complaintcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('national_id', models.CharField(max_length=20, verbose_name='ID or Passport Number')),
                ('residence_sector', models.CharField(max_length=100)),
                ('residence_cell', models.CharField(max_length=100)),
                ('residence_village', models.CharField(max_length=100)),
                ('land_sector', models.CharField(max_length=100)),
                ('land_cell', models.CharField(max_length=100)),
                ('upi', models.CharField(max_length=50, verbose_name='Parcel Identification (UPI)')),
                ('description', models.TextField(max_length=5000)),
                ('has_approached_other_institution', models.BooleanField(default=False)),
                ('other_institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_resolution_details', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='complaint_attachments/')),
                ('tracking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='administrator.complaintcategory')),
                ('citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_complaints', to=settings.AUTH_USER_MODEL)),
                ('land_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputed_lands', to='accounts.district')),
                ('land_province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputed_lands', to='accounts.province')),
                ('residence_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complainant_residences', to='accounts.district')),
                ('residence_province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complainant_residences', to='accounts.province')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
