# Generated by Django 5.0.7 on 2026-03-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='escalation_risk',
            field=models.FloatField(default=0.0, help_text='Predicted probability (0-1) of escalation.'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_escalated',
            field=models.BooleanField(default=False, help_text='True if this complaint has been escalated to higher authorities.'),
        ),
    ]
