# Generated by Django 6.0.3 on 2026-03-13 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_complaint_escalation_risk_complaint_is_escalated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The staff member handling this case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_appeal',
            field=models.BooleanField(default=False, help_text='True if this is an appeal of a previous resolution.'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_details',
            field=models.TextField(blank=True, help_text='Final outcome details.', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
