# Generated by Django 5.0.7 on 2026-05-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='referral_level',
            field=models.CharField(choices=[('none', 'None (Local Level)'), ('district', 'District Level'), ('ombudsman', 'Ombudsman'), ('court', 'Court / Judicial')], default='none', max_length=20),
        ),
    ]
