# Generated by Django 5.0.7 on 2026-03-12 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Applicable for office-type users only', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='administrator.office'),
        ),
    ]
